import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import AppMenu from "./Components/AppMenu";
export default function RootLayout({
    children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="overflow-y pb-32 pt-6">
        {children}
        </main>
        <footer >
        <AppMenu/>
        </footer>
      </body>
    </html>
  );
}
